@startuml
VaultClient -> VaultProxy: Non-GET Request or starting with /v1/sys
VaultProxy -> VaultServer: Proxy Request as is
VaultServer -> VaultProxy: Returns payload
VaultProxy -> VaultClient: Returns payload as is
@enduml